version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lab8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HackMe228
    ports:
      - "5432:5432"

  app:
    build: .
    image: myapp-image:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab8
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: HackMe228
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
